# Generated by Django 4.1.3 on 2022-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldetail',
            name='url',
            field=models.CharField(default='sa', max_length=400),
            preserve_default=False,
        ),
    ]
