# Generated by Django 5.2.10 on 2026-01-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_urldetail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldin_otkaz', models.BooleanField(default=False, verbose_name='Oldin Otkaz')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('bankshot', models.CharField(max_length=255, verbose_name='Bankshot')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Passport Number')),
                ('passport_issue', models.DateField(verbose_name='Passport Issue Date')),
                ('passport_expiry', models.DateField(verbose_name='Passport Expiry Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('zipcode', models.CharField(max_length=20, verbose_name='Zipcode')),
                ('test_type', models.CharField(choices=[('IELTS', 'IELTS'), ('TOPIK', 'TOPIK'), ('TOEFL', 'TOEFL')], max_length=10, verbose_name='Test Type')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score')),
                ('test_date', models.DateField(verbose_name='Test Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('education_level', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('college', 'College')], max_length=20, verbose_name='Education Level')),
                ('uni_phone', models.CharField(max_length=20, verbose_name='University Phone')),
                ('uni_website', models.URLField(blank=True, verbose_name='University Website')),
                ('uni_email', models.EmailField(max_length=254, verbose_name='University Email')),
                ('uni_address', models.TextField(verbose_name='University Address')),
                ('diplom_number', models.CharField(max_length=100, verbose_name='Diploma Number')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='GPA')),
                ('grad_date', models.DateField(verbose_name='Graduation Date')),
                ('prev_major', models.CharField(max_length=255, verbose_name='Previous Major')),
                ('father_name', models.CharField(max_length=255, verbose_name='Father Name')),
                ('father_passport', models.CharField(blank=True, max_length=50, verbose_name='Father Passport')),
                ('father_dob', models.DateField(blank=True, null=True, verbose_name='Father DOB')),
                ('father_phone', models.CharField(blank=True, max_length=20, verbose_name='Father Phone')),
                ('father_job', models.CharField(blank=True, max_length=255, verbose_name='Father Occupation')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Mother Name')),
                ('mother_passport', models.CharField(blank=True, max_length=50, verbose_name='Mother Passport')),
                ('mother_dob', models.DateField(blank=True, null=True, verbose_name='Mother DOB')),
                ('mother_phone', models.CharField(blank=True, max_length=20, verbose_name='Mother Phone')),
                ('mother_job', models.CharField(blank=True, max_length=255, verbose_name='Mother Occupation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='University Name')),
                ('education_level', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('college', 'College')], max_length=20, verbose_name='Education Level')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('country', models.CharField(default='Uzbekistan', max_length=100, verbose_name='Country')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
    ]
