# Generated by Django 5.2.10 on 2026-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_application_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_photos/', verbose_name='Photo'),
        ),
    ]
